# Generated by Django 3.1.5 on 2021-01-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='Message',
        ),
    ]
