# Generated by Django 3.1.5 on 2021-01-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20210108_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Contact',
        ),
    ]
